### PR TITLE
Issue #37 Fix docker installation in CI node

### LINKED ISSUE #37: Fix docker installation in CI machine
With latest upgrades in docker, it seems that docker installation is failing in CentOs machine.
This build is failing due to that - https://ci.centos.org/job/minishift-pr/503/console.

Even getting failure error in my CentOS workstation:
```
[budhram@localhost ~]$ sudo yum -y install docker-engine
Loaded plugins: fastestmirror, langpacks

File contains parsing errors: file:///etc/yum.repos.d/docker.repo
	[line  2]:   name=Docker Repository

	[line  3]:   baseurl=https://yum.dockerproject.org/repo/main/centos/7/

	[line  4]:   enabled=1

	[line  5]:   gpgcheck=1

	[line  6]:   gpgkey=https://yum.dockerproject.org/gpg

```

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #37

### CODE REVIEW

File: centos_ci.sh [hunk 1]
```diff
@@ -28,18 +28,10 @@ yum -y install \
...
-baseurl=https://yum.dockerproject.org/repo/main/centos/7/
-enabled=1
-gpgcheck=1
-gpgkey=https://yum.dockerproject.org/gpg
-EOF
-
-yum -y install docker-engine
-systemctl enable docker.service
+# Install Docker (https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository)
+yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
```
Comment (praveenkumar) [inline centos_ci.sh]: -1 , we should never you upstream docker repo to install docker, that's wrong. For our ISOs  and even for testing our features we should always use what distro have in the repo.

**Review by praveenkumar — DISMISSED** [review]

**Comment by brgnepal** [comment]
retest this please

**Comment by brgnepal** [comment]
@praveenkumar Distro version seems to be working 👍

File: centos_ci.sh [hunk 2]
```diff
@@ -27,19 +27,8 @@ yum -y install \
...
-baseurl=https://yum.dockerproject.org/repo/main/centos/7/
-enabled=1
-gpgcheck=1
-gpgkey=https://yum.dockerproject.org/gpg
-EOF
-
-yum -y install docker-engine
-systemctl enable docker.service
+# Install docker
+yum install -y docker
```
Comment (LalatenduMohanty) [inline centos_ci.sh]: @budhrg I think it is good idea to keep the `systemctl enable docker.service`. In case you want the docker to be running after a reboot.

**Review by LalatenduMohanty — DISMISSED** [review]

File: centos_ci.sh (hunk 2 above)
Comment (praveenkumar) [reply centos_ci.sh]: @LalatenduMohanty I think it's only for test and that instance is deleted once iso creation is done or tests passed/failed. No reboot cycle happen to it.

Comment (praveenkumar) [reply centos_ci.sh]: @budhrg better to do it as below why you need another yum install command when you already have.

```
# Get all the deps in
 yum -y install \
   make \
   git \
   epel-release \
   curl \
   python-setuptools \
   docker
```
